[package]
name = "mljtui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ratatui = "0.24.0"
mljcl = { git = "https://github.com/duckfromdiscord/mljcl" }
clap = "4.4.7"
crossterm = "0.27.0"
